[
  {
    "name": "presence",
    "value": "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1651076695761%2C%22v%22%3A1%7D",
    "domain": ".facebook.com",
    "path": "/",
    "expires": -1,
    "size": 75,
    "httpOnly": false,
    "secure": true,
    "session": true,
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "fr",
    "value": "0DUq49YhXYK3xhUrm.AWWDIBy61G64_nC895tKv1mJgk8.BiaW5N.Nl.AAA.0.0.BiaW5S.AWXLKcbirO8",
    "domain": ".facebook.com",
    "path": "/",
    "expires": 1658852689.591896,
    "size": 84,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "xs",
    "value": "24%3AC7TD5FzVmYz4dQ%3A2%3A1651076687%3A-1%3A3282",
    "domain": ".facebook.com",
    "path": "/",
    "expires": 1682612685.754845,
    "size": 50,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "datr",
    "value": "TW5pYncfzu6-Q5N1v5wzvYZg",
    "domain": ".facebook.com",
    "path": "/",
    "expires": 1714148688.75476,
    "size": 28,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "c_user",
    "value": "100074651446272",
    "domain": ".facebook.com",
    "path": "/",
    "expires": 1682612685.754833,
    "size": 21,
    "httpOnly": false,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "wd",
    "value": "800x600",
    "domain": ".facebook.com",
    "path": "/",
    "expires": 1651681485,
    "size": 9,
    "httpOnly": false,
    "secure": true,
    "session": false,
    "sameSite": "Lax",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  },
  {
    "name": "sb",
    "value": "TW5pYhfkipmoAskchAWJkDRF",
    "domain": ".facebook.com",
    "path": "/",
    "expires": 1714148688.754819,
    "size": 26,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "sameParty": false,
    "sourceScheme": "Secure",
    "sourcePort": 443
  }
]